// Generated by https://quicktype.io
export interface UserOrigin {
  name: string;
  url: string;
}

export interface BackendApiUser {
  id: number;
  name: string;
  status: string;
  species: string;
  type: string;
  gender: string;
  origin: UserOrigin;
  location: UserOrigin;
  image: string;
  episode: string[];
  url: string;
  created: string;
}

export interface User {
  id: number;
  name: string;
  status: string;
  species: string; 
}
 
export enum UserKeys {
  storeName = "user",
  lsKeyName = "lsUser",
}
  
export const UserEmptyState: User = {
  id: 0,
  name: "",
  status: "",
  species: "", 
};
